/*
 * Copyright (C) 2020-2026 Eduardo Gonzalez, Hervé Guillemet, Samuel Audet
 *
 * Licensed either under the Apache License, Version 2.0, or (at your option)
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation (subject to the "Classpath" exception),
 * either version 2, or any later version (collectively, the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *     http://www.gnu.org/licenses/
 *     http://www.gnu.org/software/classpath/license.html
 *
 * or as provided in the LICENSE.txt file that accompanied this code.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.bytedeco.pytorch.llm.transformers.optimization;

import org.bytedeco.pytorch.Tensor;

import java.util.List;
import java.util.Objects;

/**
 * Adafactor adaptive learning rate optimizer.
 *
 * <p>Adafactor reduces memory footprint by only storing first and second moments
 * along the first dimension (row-wise) rather than the full parameter shape.
 * See: Shazeer & Stern, "Adafactor: Adapting Learning Rates for Adaptive
 * Gradient Methods" (2018).
 *
 * <p>This is a stub wrapper. Full implementation depends on
 * {@code org.bytedeco.pytorch.optim.Adafactor} being generated by JavaCPP.
 */
public class Adafactor {

    private final org.bytedeco.pytorch.optim.Optimizer wrapped;

    /**
     * Construct an Adafactor optimizer.
     *
     * @param params      the parameters to optimize
     * @param lr          learning rate (informative; Adafactor ignores it by default)
     * @param weightDecay weight decay coefficient
     * @param beta1       first-moment decay rate
     * @param eps         epsilon for numerical stability
     */
    public Adafactor(List<Tensor> params, double lr, double weightDecay,
                     double beta1, double eps) {
        Objects.requireNonNull(params, "params");
        // TODO: Replace with real org.bytedeco.pytorch.optim.Adafactor once generated.
        // Until then, wrap with a pass-through SGD stub.
        this.wrapped = new org.bytedeco.pytorch.optim.SGD(params, (float) lr);
    }

    /** Perform a single optimization step. */
    public void step() {
        wrapped.step();
    }

    /** Clear accumulated gradients. */
    public void zero_grad() {
        wrapped.zero_grad();
    }

    /** Access the underlying optimizer. */
    public org.bytedeco.pytorch.optim.Optimizer unwrap() {
        return wrapped;
    }
}
