/*
 * Copyright (C) 2020-2026 Eduardo Gonzalez, Hervé Guillemet, Samuel Audet
 *
 * Licensed either under the Apache License, Version 2.0, or (at your option)
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation (subject to the "Classpath" exception),
 * either version 2, or any later version (collectively, the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *     http://www.gnu.org/licenses/
 *     http://www.gnu.org/software/classpath/license.html
 *
 * or as provided in the LICENSE.txt file that accompanied this code.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.bytedeco.pytorch.llm.transformers.pipeline;

import org.bytedeco.pytorch.llm.hub.HfHub;
import org.bytedeco.pytorch.llm.transformers.AutoModelForMultimodalLM;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * HF {@code pipeline("vqa")} for visual question answering.
 *
 * <p>Takes an image and a natural-language question, and returns a free-form
 * text answer generated by a vision-language model.
 *
 * <pre>{@code
 * VisualQuestionAnsweringPipeline pipe = VisualQuestionAnsweringPipeline.fromPretrained(
 *     "llava-hf/llava-1.5-7b-hf", hub);
 * String answer = pipe.call(image, "What is in this picture?");
 * }</pre>
 */
public final class VisualQuestionAnsweringPipeline {

    private final AutoModelForMultimodalLM.Bundle bundle;

    public VisualQuestionAnsweringPipeline(AutoModelForMultimodalLM.Bundle bundle) {
        this.bundle = Objects.requireNonNull(bundle, "bundle");
    }

    public static VisualQuestionAnsweringPipeline fromPretrained(String modelId, HfHub hub) throws IOException {
        return new VisualQuestionAnsweringPipeline(AutoModelForMultimodalLM.fromPretrained(modelId, hub));
    }

    public static VisualQuestionAnsweringPipeline fromPretrained(String modelId, HfHub hub,
            AutoModelForMultimodalLM.LoadOptions opts) throws IOException {
        return new VisualQuestionAnsweringPipeline(AutoModelForMultimodalLM.fromPretrained(modelId, hub, opts));
    }

    public static VisualQuestionAnsweringPipeline fromDirectory(Path dir) throws IOException {
        return new VisualQuestionAnsweringPipeline(AutoModelForMultimodalLM.fromDirectory(dir));
    }

    public AutoModelForMultimodalLM.Bundle bundle() {
        return bundle;
    }

    /** Returns the generated text answer for the given image and question. */
    public String call(Object image, String question) {
        List<Map<String, String>> messages = List.of(
                Map.of("role", "user", "content", question));
        return bundle.chat(messages);
    }

    public void close() {
        try { bundle.model().close(); } catch (Throwable ignored) {}
    }
}
