/*
 * Copyright (C) 2020-2026 Eduardo Gonzalez, Hervé Guillemet, Samuel Audet, mullerhai
 *
 * Licensed either under the Apache License, Version 2.0, or (at your option)
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation (subject to the "Classpath" exception),
 * either version 2, or any later version (collectively, the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *     http://www.gnu.org/licenses/
 *     http://www.gnu.org/software/classpath/license.html
 */
package org.bytedeco.pytorch.vision.draw;

import java.awt.image.BufferedImage;
import java.util.Arrays;

/**
 * Heatmap rendering — model-output feature maps / class-activation heatmaps /
 * Gaussian splats for visualization.
 *
 * <p>Supports:
 * <ul>
 *   <li>Per-channel {@code [H,W]} → ARGB image with a colormap</li>
 *   <li>Auto-rescale to {@code [0,1]}</li>
 *   <li>8 colormaps: viridis, plasma, inferno, magma, jet, parula, hot, gray</li>
 *   <li>Overlay blend with adjustable opacity</li>
 * </ul>
 */
public final class DHeatmap {

    public enum Colormap {
        VIRIDIS, PLASMA, INFERNO, MAGMA, JET, PARULA, HOT, GRAY, TURBO
    }

    private DHeatmap() {}

    /** Render a single-channel float {@code [H,W]} → ARGB image using {@code cmap}. */
    public static BufferedImage render(float[] data, int h, int w, Colormap cmap) {
        return render(data, h, w, cmap, 0f, 1f);
    }

    public static BufferedImage render(float[] data, int h, int w, Colormap cmap, float lo, float hi) {
        if (data.length != h * w) throw new IllegalArgumentException("data.length != h*w");
        // Auto-detect range when lo == hi
        if (hi <= lo) {
            float min = Float.POSITIVE_INFINITY, max = Float.NEGATIVE_INFINITY;
            for (float v : data) {
                if (v < min) min = v;
                if (v > max) max = v;
            }
            if (max - min < 1e-9f) { min = 0f; max = 1f; }
            lo = min;
            hi = max;
        }
        BufferedImage img = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        int[] out = new int[w * h];
        float[] lut = lut(cmap);
        for (int i = 0; i < data.length; i++) {
            float t = (data[i] - lo) / (hi - lo);
            if (t < 0f) t = 0f; else if (t > 1f) t = 1f;
            int idx = (int) Math.round(t * (lut.length / 3 - 1)) * 3;
            int r = clamp255(lut[idx]);
            int g = clamp255(lut[idx + 1]);
            int b = clamp255(lut[idx + 2]);
            out[i] = 0xFF000000 | (r << 16) | (g << 8) | b;
        }
        img.setRGB(0, 0, w, h, out, 0, w);
        return img;
    }

    /** Overlay {@code data} (single channel) onto {@code base} using {@code opacity}. */
    public static void overlay(DrawingCanvas c, float[] data, int h, int w,
                               Colormap cmap, float opacity) {
        BufferedImage hm = render(data, h, w, cmap);
        c.save();
        c.setOpacity(opacity);
        c.drawImage(hm, DRect.of(0, 0, c.width(), c.height()));
        c.restore();
    }

    // ---- LUTs (256 entries each, RGB) -------------------------------------

    private static float[] lut(Colormap cmap) {
        switch (cmap) {
            case VIRIDIS: return viridis;
            case PLASMA: return plasma;
            case INFERNO: return inferno;
            case MAGMA: return magma;
            case JET: return jet;
            case PARULA: return parula;
            case HOT: return hot;
            case GRAY: return gray;
            case TURBO: return turbo;
            default: return viridis;
        }
    }

    private static int clamp255(float v) {
        if (v < 0f) return 0;
        if (v > 255f) return 255;
        return Math.round(v);
    }

    // ---- pre-computed 256-entry LUTs --------------------------------------
    // Generated by the matplotlib-style stops, hand-compressed. Values in [0,255].

    private static float[] gray = ramp(0, 255, 0, 255, 0, 255);

    private static float[] hot = chain(new float[][]{
            ramp(0, 0, 31, 0, 0, 0),       ramp(0, 31, 95, 0, 0, 0),
            ramp(95, 159, 255, 0, 0, 0),  ramp(255, 255, 255, 0, 0, 0)
    });

    private static float[] jet = chain(new float[][]{
            ramp(0, 0, 127, 0, 0, 0),
            ramp(0, 0, 255, 127, 0, 0),
            ramp(0, 255, 255, 255, 0, 0),
            ramp(127, 255, 255, 255, 127, 0),
            ramp(255, 255, 255, 255, 255, 127),
            ramp(255, 191, 127, 255, 255, 255)
    });

    private static float[] viridis = chain(new float[][]{
            {68,1,84},   {71,17,100}, {72,31,112}, {70,45,123}, {65,58,131},
            {59,72,135}, {52,85,138}, {46,98,139}, {40,112,140}, {35,125,141},
            {30,138,142}, {31,152,139}, {40,165,128}, {62,178,107}, {92,190,84},
            {132,201,58},{173,209,46},{215,216,39},{253,220,39},{254,225,54},
            {255,230,71},{255,235,89},{255,240,107},{255,246,127},{255,251,148},
            {255,255,170},{247,252,185},{232,250,199},{210,247,211},{183,243,219},
            {153,237,223},{123,229,224},{97,219,224},{78,206,222},{68,193,217},
            {63,178,210},{62,162,200},{62,146,189},{63,130,178},{66,113,165},
            {71,96,152},{78,80,138},{85,66,123},{91,53,109},{95,42,96},
            {98,33,84},{100,28,73},{101,25,63},{101,24,55},{99,24,47},
            {95,25,40},{89,26,34},{82,27,29},{74,28,25},{66,28,23}
    });

    private static float[] plasma = chain(new float[][]{
            {12,7,134}, {36,12,141}, {56,16,147}, {75,21,151}, {94,25,153},
            {113,28,153},{130,30,152},{147,32,150},{163,33,147},{179,35,143},
            {194,38,138},{209,41,132},{222,46,125},{234,52,117},{244,61,108},
            {253,72,99},{255,86,87},{255,99,78},{255,113,69},{255,128,61},
            {255,142,54},{255,157,47},{255,171,41},{255,186,35},{255,201,30},
            {255,216,26},{253,229,29},{246,240,40},{234,248,60},{219,252,87},
            {203,253,116},{188,251,143},{173,247,168},{159,242,190},{147,234,209},
            {137,224,224},{129,213,234},{122,200,239},{119,186,239},{117,172,236},
            {115,158,231},{113,144,224},{110,131,215},{107,118,205},{103,106,194},
            {99,94,182},{95,84,170},{90,74,158},{85,65,145},{79,57,131},
            {73,50,117},{66,43,103},{59,37,89},{51,31,76},{44,26,64},
            {37,21,53},{30,17,43},{24,13,35},{18,10,28},{13,7,22}
    });

    private static float[] inferno = chain(new float[][]{
            {0,0,4},    {10,7,33},  {24,11,60},  {40,14,84},  {58,17,102},
            {76,19,117},{94,21,128},{110,24,135},{126,26,141},{142,28,145},
            {157,29,147},{171,30,148},{185,31,147},{199,32,146},{212,32,143},
            {224,32,140},{235,32,136},{245,32,131},{253,33,124},{255,38,116},
            {255,46,107},{255,55,97},{255,65,87},{255,75,76},{255,86,66},
            {255,97,57},{255,109,50},{255,121,44},{255,134,39},{255,146,35},
            {255,159,32},{255,172,30},{255,186,29},{255,199,30},{255,212,34},
            {255,224,42},{255,234,56},{253,243,75},{247,250,98},{237,255,124},
            {223,255,151},{206,253,178},{188,247,202},{170,238,222},{151,227,238},
            {132,213,247},{115,198,251},{100,182,250},{87,165,243},{77,148,233},
            {69,131,219},{62,114,202},{57,98,184},{52,84,164},{47,71,144},
            {42,60,124},{37,51,107},{32,43,91},{27,36,77},{22,30,65},
            {17,25,55},{12,20,46},{8,16,38},{5,12,30},{2,8,23}
    });

    private static float[] magma = chain(new float[][]{
            {0,0,3},    {7,6,28},   {19,9,51},   {34,12,72},  {52,15,88},
            {70,17,102},{89,19,113},{108,21,121},{127,23,127},{145,25,131},
            {162,26,134},{179,28,136},{195,29,136},{210,30,136},{224,32,134},
            {236,34,131},{246,38,127},{254,43,121},{255,52,114},{255,63,105},
            {255,75,95},{255,87,85},{255,99,75},{255,111,65},{255,124,56},
            {255,137,47},{255,150,40},{255,164,34},{255,178,30},{255,192,29},
            {255,206,31},{255,220,38},{253,232,52},{247,243,73},{237,251,99},
            {225,255,127},{211,255,154},{196,254,178},{181,249,199},{165,242,217},
            {149,232,231},{133,220,239},{118,206,243},{104,191,243},{92,175,239},
            {81,158,231},{71,141,220},{62,124,206},{54,108,191},{47,93,174},
            {41,79,157},{35,67,139},{30,57,122},{25,48,105},{21,40,89},
            {17,33,74},{13,27,61},{9,22,49},{6,17,38},{3,13,29}
    });

    private static float[] parula = chain(new float[][]{
            {53,42,135}, {60,53,144}, {65,64,153}, {69,75,161}, {72,86,168},
            {73,96,173}, {73,106,177}, {72,115,180}, {70,124,182}, {66,132,182},
            {62,140,182}, {57,148,181}, {52,156,180}, {47,164,179}, {42,171,178},
            {39,179,177}, {37,186,176}, {37,193,174}, {40,200,171}, {47,206,167},
            {58,212,162}, {73,217,156}, {93,221,148}, {117,225,139}, {145,228,128},
            {176,229,116},{209,228,103},{242,224,90},{253,213,72},{254,199,57},
            {254,185,46},{254,170,38},{253,156,33},{252,141,29},{251,127,27},
            {249,113,25},{246,99,24},{242,86,23},{237,73,22},{231,61,21},
            {224,50,19},{216,40,17},{208,30,15},{199,22,12},{189,16,9},
            {179,12,6},{168,9,3},{157,7,1},{146,5,0},{135,4,0}
    });

    private static float[] turbo = chain(new float[][]{
            {48,18,59}, {50,21,67}, {51,24,74}, {52,27,81}, {53,30,88},
            {54,33,95}, {55,36,102},{56,39,109},{57,42,115},{58,45,121},
            {59,47,128},{60,50,134},{61,53,139},{62,56,145},{63,59,151},
            {63,62,156},{64,64,162},{65,67,167},{65,70,172},{66,73,177},
            {66,75,181},{67,78,186},{68,81,191},{68,84,195},{68,86,199},
            {69,89,203},{69,92,207},{69,94,211},{70,97,214},{70,100,218},
            {70,102,221},{70,105,224},{70,107,227},{71,110,230},{71,113,233},
            {71,115,235},{71,118,238},{71,120,240},{71,123,242},{70,125,244},
            {70,128,246},{70,130,248},{70,133,250},{69,135,251},{69,138,252},
            {68,140,253},{67,143,254},{66,145,254},{65,148,255},{64,150,255},
            {63,153,255},{62,155,254},{61,158,254},{59,160,253},{58,163,252},
            {56,165,251},{55,168,250},{53,171,248},{51,173,247},{49,175,245},
            {47,178,244},{45,180,242},{43,183,240},{41,185,238},{39,187,236},
            {37,190,233},{35,192,231},{33,194,229},{31,197,226},{29,199,223},
            {27,201,221},{25,203,218},{23,205,215},{21,207,212},{19,209,209},
            {18,211,206},{16,213,202},{15,215,199},{14,216,196},{13,218,192},
            {13,220,189},{13,222,186},{14,223,182},{16,225,179},{19,226,175},
            {24,228,172},{31,229,168},{40,230,164},{51,231,160},{64,232,156},
            {79,233,151},{96,233,147},{114,234,142},{134,234,137},{154,234,131},
            {175,233,125},{195,232,118},{215,231,110},{234,229,102},{251,226,93}
    });

    // ---- ramp helpers -----------------------------------------------------

    /** Linear ramp from one RGB triple to another. */
    private static float[] ramp(int r1, int g1, int b1, int r2, int g2, int b2) {
        float[] o = new float[256 * 3];
        for (int i = 0; i < 256; i++) {
            float t = i / 255f;
            o[i * 3 + 0] = r1 + (r2 - r1) * t;
            o[i * 3 + 1] = g1 + (g2 - g1) * t;
            o[i * 3 + 2] = b1 + (b2 - b1) * t;
        }
        return o;
    }

    /** Piecewise ramp from a sequence of stops. */
    private static float[] chain(float[][] stops) {
        // stops[i] has length 3. Spread evenly.
        float[] o = new float[256 * 3];
        int n = stops.length;
        int segSize = 256 / (n - 1);
        int[] ends = new int[n];
        for (int i = 0; i < n; i++) ends[i] = Math.min(255, i * segSize);
        ends[n - 1] = 255;
        for (int s = 0; s < n - 1; s++) {
            int start = ends[s];
            int end = ends[s + 1];
            for (int i = start; i <= end; i++) {
                float t = (i - start) / (float) Math.max(1, end - start);
                o[i * 3 + 0] = stops[s][0] + (stops[s + 1][0] - stops[s][0]) * t;
                o[i * 3 + 1] = stops[s][1] + (stops[s + 1][1] - stops[s][1]) * t;
                o[i * 3 + 2] = stops[s][2] + (stops[s + 1][2] - stops[s][2]) * t;
            }
        }
        return o;
    }
}