/*
 * Copyright (C) 2020-2026 Eduardo Gonzalez, Hervé Guillemet, Samuel Audet
 *
 * Licensed either under the Apache License, Version 2.0, or (at your option)
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation (subject to "Classpath" exception),
 * either version 2, or any later version (collectively, the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *     http://www.gnu.org/licenses/
 *     http://www.gnu.org/software/classpath/license.html
 *
 * or as provided in the LICENSE.txt file that accompanied this code.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.bytedeco.pytorch.llm.transformers.modeling_utils;

import org.bytedeco.pytorch.Tensor;
import org.bytedeco.pytorch.nn.Module;

import java.util.HashMap;
import java.util.Map;

/**
 * Module utilities: parameter inspection and helpers.
 *
 * <p>Reference: HuggingFace transformers
 * {@code modeling_utils.ModuleUtilsMixin}.
 */
public final class ModuleUtils {

    private ModuleUtils() {}

    /**
     * Collect all named parameters from a module (recursively).
     *
     * @param m module to inspect
     * @return map of parameter name to tensor
     */
    public static Map<String, Tensor> named_parameters(Module m) {
        if (m == null) return Map.of();
        org.bytedeco.pytorch.StringTensorDict dict = m.named_parameters(/*recurse=*/true);
        if (dict == null || dict.isNull()) return Map.of();
        return dict.toMap();
    }

    /**
     * Count total number of parameters in a module.
     */
    public static long count_parameters(Module m) {
        return named_parameters(m).values().stream()
                .mapToLong(t -> t != null ? t.numel() : 0L)
                .sum();
    }

    /**
     * Get parameter dtype.
     */
    public static String dtype(Module m) {
        Map<String, Tensor> params = named_parameters(m);
        if (params.isEmpty()) return "unknown";
        Tensor first = params.values().iterator().next();
        return first != null ? first.dtype().toString() : "unknown";
    }

    /**
     * Minimal map wrapper mirroring the native StringTensorDict interface.
     * This is a placeholder; the actual native type is generated by JavaCPP.
     */
    public static class StringTensorDict {
        private final Map<String, Tensor> map;

        public StringTensorDict(Map<String, Tensor> map) {
            this.map = new HashMap<>(map);
        }

        public boolean isNull() { return map == null || map.isEmpty(); }
        public long size() { return map.size(); }
        public Tensor get(String key) { return map.get(key); }
        public Map<String, Tensor> toMap() { return Map.copyOf(map); }
    }
}
